In [1]:
import pandas as pd
import numpy as np

In [4]:
data= pd.read_csv("kc_house_data1_cleaned.csv")
data
#data.head()

,id,date,bedrooms,bathrooms,sqft_living,sqft_above,grade,price
0,7129300520,20141013T000000,3,1.00,1180,1180,7,221900.0
1,6414100192,20141209T000000,3,2.25,2570,2170,7,538000.0
2,5631500400,20150225T000000,2,1.00,770,770,6,180000.0
3,2487200875,20141209T000000,4,3.00,1960,1050,7,604000.0
4,1954400510,20150218T000000,3,2.00,1680,1680,8,510000.0
5,7237550310,20140512T000000,4,4.50,5420,3890,11,1225000.0
6,1321400060,20140627T000000,3,2.25,1715,1715,7,257500.0
7,2008000270,20150115T000000,3,1.50,1060,1060,7,291850.0
8,2414600126,20150415T000000,3,1.00,1780,1050,7,229500.0
9,3793500160,20150312T000000,3,2.50,1890,1890,7,323000.0
10,1736800520,20150403T000000,3,2.50,3560,1860,8,662500.0
11,9212900260,20140527T000000,2,1.00,1160,860,7,468000.0
12,114101516,20140528T000000,3,1.00,1430,1430,7,310000.0
13,6054650070,20141007T000000,3,1.75,1370,1370,7,400000.0
14,1175000570,20150312T000000,5,2.00,1810,1810,7,530000.0
15,9297300055,20150124T000000,4,3.00,2950,1980,9,650000.0
16,1875500060,20140731T000000,3,2.00,1890,1890,7,395000.0
17,6865200140,20140529T000000,4,1.00,1600,1600,7,485000.0
18,16000397,20141205T000000,2,1.00,1200,1200,7,189000.0
19,7983200060,20150424T000000,3,1.00,1250,1250,7,230000.0
20,6300500875,20140514T000000,4,1.75,1620,860,7,385000.0
21,2524049179,20140826T000000,3,2.75,3050,2330,9,2000000.0
22,7137970340,20140703T000000,5,2.50,2270,2270,8,285000.0
23,8091400200,20140516T000000,2,1.50,1070,1070,7,252700.0
24,3814700200,20141120T000000,3,2.25,2450,2450,8,329000.0
25,1202000200,20141103T000000,3,2.00,1710,1710,6,233000.0
26,1794500383,20140626T000000,3,1.75,2450,1750,8,937000.0
27,3303700376,20141201T000000,3,1.00,1400,1400,8,667000.0
28,5101402488,20140624T000000,3,1.75,1520,790,7,438000.0
29,1873100390,20150302T000000,4,2.50,2570,2570,8,719000.0
...,...,...,...,...,...,...,...,...
21515,2025049203,20140610T000000,2,1.00,710,710,7,399950.0
21516,952006823,20141202T000000,3,2.50,1260,940,7,380000.0
21517,3832050760,20140828T000000,3,2.50,1870,1870,7,270000.0
21518,2767604724,20141015T000000,2,2.50,1430,1430,8,505000.0
21519,6632300207,20150305T000000,3,2.50,1520,1520,8,385000.0
21520,2767600688,20141113T000000,2,1.50,1210,1020,8,414500.0
21521,7570050450,20140910T000000,3,2.50,2540,2540,8,347500.0
21522,7430200100,20140514T000000,4,3.50,4910,3110,11,1222500.0
21523,4140940150,20141002T000000,4,2.75,2770,2770,8,572000.0
21524,1931300412,20150416T000000,3,2.25,1190,1190,8,475000.0
21525,8672200110,20150317T000000,5,3.75,4170,4170,10,1088000.0
21526,5087900040,20141017T000000,4,2.75,2500,2500,8,350000.0
21527,1972201967,20141031T000000,2,2.25,1530,1480,8,520000.0
21528,7502800100,20140813T000000,5,2.75,3600,3600,9,679950.0
21529,191100405,20150421T000000,4,3.25,3410,3410,10,1575000.0
21530,8956200760,20141013T000000,4,2.50,3118,3118,9,541800.0
21531,7202300110,20140915T000000,4,3.00,3990,3990,9,810000.0
21532,249000205,20141015T000000,5,3.75,4470,4470,11,1537000.0
21533,5100403806,20150407T000000,3,2.50,1425,1425,8,467000.0
21534,844000965,20140626T000000,3,1.75,1500,1500,6,224000.0
21535,7852140040,20140825T000000,3,2.50,2270,2270,8,507250.0
21536,9834201367,20150126T000000,3,2.00,1490,1490,8,429000.0
21537,3448900210,20141014T000000,4,2.50,2520,2520,9,610685.0
21538,7936000429,20150326T000000,4,3.50,3510,2600,9,1007500.0
21539,2997800021,20150219T000000,3,2.50,1310,1180,8,475000.0
21540,263000018,20140521T000000,3,2.50,1530,1530,8,360000.0
21541,6600060120,20150223T000000,4,2.50,2310,2310,8,400000.0
21542,1523300141,20140623T000000,2,0.75,1020,1020,7,402101.0
21543,291310100,20150116T000000,3,2.50,1600,1600,8,400000.0
21544,1523300157,20141015T000000,2,0.75,1020,1020,7,325000.0

In [ ]:
data.shape

In [ ]:
data.info()

In [ ]:
data.isnull().sum()

In [ ]:
X = data[['bedrooms','bathrooms','sqft_living','sqft_above','grade']]

In [ ]:
y = data['price']

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,
                                               random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)

In [ ]:
y_pred = reg.predict(X_test)

In [ ]:
print('Coefficients: \n', reg.coef_)
print('Intercept: \n', reg.intercept_)

In [ ]:
from sklearn import metrics
print(metrics.mean_squared_error(y_test, y_pred))

In [ ]:
metrics.r2_score(y_test, y_pred)